/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolibres;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.Writer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pa
 */
public class ListaGastos extends javax.swing.JFrame {

    /**
     * Creates new form ListaGastos
     */
    DefaultListModel lista = new DefaultListModel();
    DefaultComboBoxModel modelo;
    XMLManager form;
    private int posicion = -1;
    Object gastoNegocio;

    public ListaGastos(XMLManager formAux, int pos, Object obj, DefaultListModel list) {
        initComponents();
        this.form = formAux;
        this.posicion = pos;
        this.gastoNegocio = obj;

        this.lista = list;

        jListGastos.setModel(lista);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public ListaGastos(XMLManager formAux, DefaultListModel list) {
        initComponents();

        this.form = formAux;

        this.lista = list;

        jListGastos.setModel(lista);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void agregarElementos() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListGastos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jTextFieldIngresoGasto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListGastos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Gastos de Negocio");

        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ingresar tipo de gasto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIngresoGasto))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIngresoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEliminar)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonSalir)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed

        File nombreArchivo = new File("src/GastosNegocio/tipoGastos.txt");

        jListGastos.setModel(lista);

        if (jTextFieldIngresoGasto.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Ingrese un nuevo tipo de gasto");

        } else {

            lista.addElement(jTextFieldIngresoGasto.getText());

        }

        for (int i = 0; i < lista.size(); i++) {

            if (lista.getElementAt(i).equals("Alimentacion")) {

                lista.removeElementAt(i);
            }

            if (lista.getElementAt(i).equals("Educacion")) {

                lista.removeElementAt(i);
            }

            if (lista.getElementAt(i).equals("Vivienda")) {

                lista.removeElementAt(i);
            }

            if (lista.getElementAt(i).equals("Salud")) {

                lista.removeElementAt(i);
            }

            if (lista.getElementAt(i).equals("Vestimenta")) {

                lista.removeElementAt(i);
            }

            if (lista.getElementAt(i).equals("Otros Gastos")) {

                lista.removeElementAt(i);
            }

            if (lista.getElementAt(i).equals("Agregar Gasto de Negocio")) {

                lista.removeElementAt(i);
            }

        }

        lista.add(lista.size(), "Alimentacion");
        lista.add(lista.size(), "Educacion");
        lista.add(lista.size(), "Vivienda");
        lista.add(lista.size(), "Salud");
        lista.add(lista.size(), "Vestimenta");
        lista.add(lista.size(), "Otros Gastos");
        lista.add(lista.size(), "Agregar Gasto de Negocio");

        try {

            FileWriter fw = new FileWriter(nombreArchivo);

            Writer salida = new BufferedWriter(fw);

            for (int i = 0; i < lista.size(); i++) {

                salida.write(lista.get(i) + "\r\n");

            }

            salida.close();

        } catch (Exception e) {

        }

        if (posicion >= 0) {

            form.tablaNegocio.setValueAt(jTextFieldIngresoGasto.getText(), posicion, 2);

            modelo = new DefaultComboBoxModel(lista.toArray());

            form.comboBoxNegocio.setModel(modelo);

            form.jComboBoxTipoGastoNegocio.setModel(modelo);

        } else {

            modelo = new DefaultComboBoxModel(lista.toArray());

            form.comboBoxNegocio.setModel(modelo);

            form.jComboBoxTipoGastoNegocio.setModel(modelo);
            
            form.jComboBoxTipoGastoNegocio.setSelectedItem(jTextFieldIngresoGasto.getText());
            
            for(int i=0; i < form.tablaNegocio.getRowCount();i++){
                
            
                form.tablaNegocio.setValueAt(form.jComboBoxTipoGastoNegocio.getSelectedItem(), i, 2);
            }

        }

        jTextFieldIngresoGasto.setText("");

        //form.datosLista = lista;
        JOptionPane.showMessageDialog(null, "Tipo de gasto agregado correctamente");

    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        File nombreArchivo = new File("src/GastosNegocio/tipoGastos.txt");

        int index = jListGastos.getSelectedIndex();

        jTextFieldIngresoGasto.setText("");

        if (jListGastos.getSelectedIndex() < 0) {

            JOptionPane.showMessageDialog(null, "Seleccione un tipo de gasto para eliminar");

        } else {

            lista.removeElementAt(index);

        }

        try {

            FileWriter fw = new FileWriter(nombreArchivo);

            Writer salida = new BufferedWriter(fw);

            for (int i = 0; i < lista.size(); i++) {

                salida.write(lista.get(i) + "\r\n");

            }

            salida.close();

        } catch (Exception e) {

        }

        modelo = new DefaultComboBoxModel(lista.toArray());

        form.comboBoxNegocio.setModel(modelo);

        form.jComboBoxTipoGastoNegocio.setModel(modelo);

        JOptionPane.showMessageDialog(null, "Tipo de gasto eliminado correctamente");


    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        modelo = new DefaultComboBoxModel(lista.toArray());

        form.comboBoxNegocio.setModel(modelo);

        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //               new ListaGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListGastos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldIngresoGasto;
    // End of variables declaration//GEN-END:variables
}
