/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolibres;

import ConexionBDD.Conexion;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jairo
 */
public class Reportes extends javax.swing.JFrame {
   
   String []temaReporte;
    String []reporteCabezera;
    Object [][]reporteMatriz;
    static Connection con;
    JTable reporteProveedor;
    JTable reporteTipoGasto;
    JTable reporteCantidadFacturas;
    Conexion conn;
    /**
     * Creates new form Reportes
     * 
     */
    public Reportes() {
        initComponents();
        temaReporte=new String[4];
        temaReporte[3]="khe";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelRESULTADOS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxProveedores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabelProveedorSeleccionado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btn_consultar = new javax.swing.JButton();
        jPanelRESULTADOS1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabelTipoGastoSeleccionado = new javax.swing.JLabel();
        btn_tipoGasto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jComboBoxClientes = new javax.swing.JComboBox<>();
        jLabelClienteSeleccionado = new javax.swing.JLabel();
        jLabelSeleccionCliente = new javax.swing.JLabel();
        jLabelSeleccionTipoGasto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPaneReporteCountAnual = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxReporteAnio = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxReporteCliente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxReporteProveedor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxClienteNegocio = new javax.swing.JComboBox<>();
        jComboBoxAnioNegocio = new javax.swing.JComboBox<>();
        jComboBoxTipoGasto = new javax.swing.JComboBox<>();
        jButtonConsultar = new javax.swing.JButton();
        jScrollPaneGastoNegocio = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REPORTES");
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanelRESULTADOS.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Reporte de Proveedor");

        jComboBoxProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Proveedor:");

        jLabelProveedorSeleccionado.setText("Sin Seleccionar");

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRESULTADOSLayout = new javax.swing.GroupLayout(jPanelRESULTADOS);
        jPanelRESULTADOS.setLayout(jPanelRESULTADOSLayout);
        jPanelRESULTADOSLayout.setHorizontalGroup(
            jPanelRESULTADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRESULTADOSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRESULTADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelRESULTADOSLayout.createSequentialGroup()
                        .addGroup(jPanelRESULTADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanelRESULTADOSLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProveedorSeleccionado))
                            .addGroup(jPanelRESULTADOSLayout.createSequentialGroup()
                                .addComponent(jComboBoxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)
                                .addComponent(btn_consultar)))
                        .addGap(0, 543, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRESULTADOSLayout.setVerticalGroup(
            jPanelRESULTADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRESULTADOSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelRESULTADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRESULTADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelProveedorSeleccionado))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proveedor", jPanelRESULTADOS);

        jPanelRESULTADOS1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Reporte de Tipo de Gasto");

        jComboBoxTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Cliente:");

        jLabelTipoGastoSeleccionado.setText("Sin Seleccionar");

        btn_tipoGasto.setText("Consultar");
        btn_tipoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tipoGastoActionPerformed(evt);
            }
        });

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabelClienteSeleccionado.setText("Sin Seleccionar");

        jLabelSeleccionCliente.setText("Seleccionar cliente:");

        jLabelSeleccionTipoGasto.setText("Seleccionar tipo de gasto:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Tipo de gasto:");

        javax.swing.GroupLayout jPanelRESULTADOS1Layout = new javax.swing.GroupLayout(jPanelRESULTADOS1);
        jPanelRESULTADOS1.setLayout(jPanelRESULTADOS1Layout);
        jPanelRESULTADOS1Layout.setHorizontalGroup(
            jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRESULTADOS1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanelRESULTADOS1Layout.createSequentialGroup()
                        .addGroup(jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabelSeleccionCliente)
                            .addComponent(jLabelSeleccionTipoGasto))
                        .addGap(38, 38, 38)
                        .addGroup(jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRESULTADOS1Layout.createSequentialGroup()
                                .addGroup(jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelClienteSeleccionado)
                                    .addComponent(jLabelTipoGastoSeleccionado))
                                .addGap(46, 46, 46)
                                .addComponent(btn_tipoGasto))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRESULTADOS1Layout.setVerticalGroup(
            jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRESULTADOS1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRESULTADOS1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeleccionCliente))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeleccionTipoGasto))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelClienteSeleccionado))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelRESULTADOS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabelTipoGastoSeleccionado)))
                    .addGroup(jPanelRESULTADOS1Layout.createSequentialGroup()
                        .addComponent(btn_tipoGasto)
                        .addGap(4, 4, 4)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tipo de gasto", jPanelRESULTADOS1);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Reporte 1 ");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Exportar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Año:");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("Cliente :");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Proveedor");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("Filtros");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Consultar General");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(90, 90, 90)
                        .addComponent(jComboBoxReporteCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(117, 117, 117)
                        .addComponent(jComboBoxReporteAnio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(75, 75, 75)
                        .addComponent(jComboBoxReporteProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxReporteAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxReporteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxReporteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneReporteCountAnual)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 395, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneReporteCountAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Anual", jPanel1);

        jLabel11.setText("Filtros:");

        jLabel12.setText("Cliente:");

        jLabel13.setText("Año:");

        jLabel14.setText("Tipo de Gasto:");

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(121, 121, 121)
                        .addComponent(jComboBoxClienteNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonConsultar)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(81, 81, 81)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxAnioNegocio, 0, 140, Short.MAX_VALUE)
                                .addComponent(jComboBoxTipoGasto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxClienteNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxAnioNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConsultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneGastoNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPaneGastoNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gastos de Negocio", jPanel4);

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Regresar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleName("File");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(250, 250, 250))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       regresar();
       this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
                               
            setPanelReportes(jComboBoxProveedores.getSelectedItem().toString());
            jLabelProveedorSeleccionado.setText((String)jComboBoxProveedores.getSelectedItem());
        
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_tipoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tipoGastoActionPerformed

        setPanelTipoGasto(jComboBoxTipos.getSelectedItem().toString());
        jLabelTipoGastoSeleccionado.setText((String)jComboBoxTipos.getSelectedItem());
    }//GEN-LAST:event_btn_tipoGastoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       setPanelReporteAnual();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      generarReportes();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setPanelCantidadFacturas(jComboBoxReporteCliente.getSelectedItem().toString());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
       
        setPanelReporteNegocios();
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_tipoGasto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JComboBox<String> jComboBoxAnioNegocio;
    private javax.swing.JComboBox<String> jComboBoxClienteNegocio;
    private javax.swing.JComboBox<String> jComboBoxClientes;
    private javax.swing.JComboBox<String> jComboBoxProveedores;
    private javax.swing.JComboBox<String> jComboBoxReporteAnio;
    private javax.swing.JComboBox<String> jComboBoxReporteCliente;
    private javax.swing.JComboBox<String> jComboBoxReporteProveedor;
    private javax.swing.JComboBox<String> jComboBoxTipoGasto;
    private javax.swing.JComboBox<String> jComboBoxTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClienteSeleccionado;
    private javax.swing.JLabel jLabelProveedorSeleccionado;
    private javax.swing.JLabel jLabelSeleccionCliente;
    private javax.swing.JLabel jLabelSeleccionTipoGasto;
    private javax.swing.JLabel jLabelTipoGastoSeleccionado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelRESULTADOS;
    private javax.swing.JPanel jPanelRESULTADOS1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneGastoNegocio;
    private javax.swing.JScrollPane jScrollPaneReporteCountAnual;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void setCombos(){
        setComboProveedores();
        setComboTipoGastos();
        setComboClientes();
        
       this.setComboReportes();
    }
   private void setComboProveedores(){
       
                    
            ArrayList<String> proveedores = new ConexionBDD.Conexion().consultarProveedores();
            
            
            this.jComboBoxProveedores.removeAllItems();
            for(String prov: proveedores){
                this.jComboBoxProveedores.addItem(prov);
                
            }
            this.jComboBoxProveedores.setSelectedIndex(0);
            
            jLabelProveedorSeleccionado.setText((String)jComboBoxProveedores.getSelectedItem());
        
        
        this.jComboBoxProveedores.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
               jLabelProveedorSeleccionado.setText((String)e.getItem());
               
            }
        });
                    
    }
   private void setComboReportes(){
       this.setComboReporteAnual();
       this.setComboReporteCliente();
       this.setComboReporteProveedor();
       this.setComboClientesNegocio();
       this.setComboAniosNegocio();
       this.setComboTipoGastosNegocio();
       
   }
   
   
   private void setComboReporteProveedor(){
         ArrayList<String> proveedores = new ConexionBDD.Conexion().consultarProveedores();
            
            
            this.jComboBoxReporteProveedor.removeAllItems();
            this.jComboBoxReporteProveedor.addItem("Todos");
            for(String prov: proveedores){
                this.jComboBoxReporteProveedor.addItem(prov);
                
            }
            this.jComboBoxReporteProveedor.setSelectedIndex(0);
       
   }
   
   private void setComboReporteCliente(){
        ArrayList<String> clientes = new ConexionBDD.Conexion().consultarClientes();
            
            
            this.jComboBoxReporteCliente.removeAllItems();
        
            for(String prov: clientes){
                this.jComboBoxReporteCliente.addItem(prov);
                
            }
            this.jComboBoxReporteCliente.setSelectedIndex(0);
   }
   
   private void setComboReporteAnual() {
     //Aquiva la consulta de los anios en la base 
     ArrayList<String> anios = new ConexionBDD.Conexion().consultarAnios();
     this.jComboBoxReporteAnio.removeAllItems();
     
     for (String prov:anios){
         this.jComboBoxReporteAnio.addItem(prov);
     }
     this.jComboBoxReporteAnio.setSelectedIndex(0);
    }
   
   private void setComboClientesNegocio() {
     //Aquiva la consulta de los anios en la base 
     ArrayList<String> anios = new ConexionBDD.Conexion().consultarClientes();
     this.jComboBoxClienteNegocio.removeAllItems();
     
     for (String prov:anios){
         this.jComboBoxClienteNegocio.addItem(prov);
     }
     this.jComboBoxClienteNegocio.setSelectedIndex(0);
    }
   
    private void setComboAniosNegocio() {
     //Aquiva la consulta de los anios en la base 
     ArrayList<String> anios = new ConexionBDD.Conexion().consultarAnios();
     this.jComboBoxAnioNegocio.removeAllItems();
     
     for (String prov:anios){
         this.jComboBoxAnioNegocio.addItem(prov);
     }
     this.jComboBoxAnioNegocio.setSelectedIndex(0);
    }
    
    private void setComboTipoGastosNegocio() {
     //Aquiva la consulta de los anios en la base 
     ArrayList<String> anios = new ConexionBDD.Conexion().consultarTipoGastos();
     this.jComboBoxTipoGasto.removeAllItems();
     
     for (String prov:anios){
         this.jComboBoxTipoGasto.addItem(prov);
     }
     this.jComboBoxTipoGasto.setSelectedIndex(0);
    }
   
   
   
   private void setComboClientes(){
       
                    
            ArrayList<String> clientes = new ConexionBDD.Conexion().consultarClientes();
            
            
            this.jComboBoxClientes.removeAllItems();
            
            for(String prov: clientes){
                this.jComboBoxClientes.addItem(prov);
                
            }
            this.jComboBoxClientes.setSelectedIndex(0);
            
            jLabelClienteSeleccionado.setText((String)jComboBoxClientes.getSelectedItem());
        
        
        this.jComboBoxClientes.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
               jLabelClienteSeleccionado.setText((String)e.getItem());
               
            }
        });
                    
    }

   private void setComboTipoGastos(){
        
            ArrayList<String> tipoGastos = new ArrayList<>();
            
            tipoGastos.add("VIVIENDA");
            tipoGastos.add("SALUD");
            tipoGastos.add("EDUCACIÓN");
            tipoGastos.add("ALIMENTACIÓN");
            tipoGastos.add("VESTIMENTA");
            tipoGastos.add("OTROS");
            
            this.jComboBoxTipos.removeAllItems();
            for(String prov: tipoGastos){
                this.jComboBoxTipos.addItem(prov);
                
            }
            this.jComboBoxTipos.setSelectedIndex(0);
        
            jLabelTipoGastoSeleccionado.setText((String)jComboBoxTipos.getSelectedItem());
        
        this.jComboBoxTipos.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
               jLabelTipoGastoSeleccionado.setText((String)e.getItem());
                           }
        });
    }
    
   private void setPanelTipoGasto(String tipoGasto){
       
       conn = new Conexion();
            
            //con = Conexion.conecxionBDD();
            
            List<String[]> datos = conn.consultarFacturaTipoGastos(tipoGasto, (String) jComboBoxClientes.getSelectedItem());
            
            Object [][] matriz = datos(datos);
            
            String nombreCabeceras[] = {"GASTO TOTAL " + tipoGasto};

        
        reporteTipoGasto = new JTable(matriz, nombreCabeceras) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2;
            }
        };
        
        jScrollPane2.setViewportView(reporteTipoGasto);
       
    }
        private void setPanelReportes(String proveedor){

            //SE INSTANCIAL LA tabla reporteProveedores
            //en el panel jPanelRESULTADOS

                        // TODO add your handling code here:
                    conn = new Conexion();

                    //con = Conexion.conecxionBDD();

                    List<String[]> datos = conn.consultarFacturaPorProveedor(proveedor);

                    Object [][] matriz = datos(datos);

                    String nombreCabeceras[] = {"ID FACTURA","NOMBRE CLIENTE" ,"NOMBRE PROVEEDOR","FECHA","TOTAL ALIMENTACION", "TOTAL VESTIMENTA","TOTAL VIVIENDA",
                        "TOTAL SALUD", "TOTAL EDUCACION" ,"TOTAL OTROS","TOTAL SIN IVA", "IVA","TOTAL CON IVA"};



                reporteProveedor = new JTable(matriz, nombreCabeceras) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return column == 2;
                    }
                };

                jScrollPane1.setViewportView(reporteProveedor);



        }

        public Object [][] datos (List<String []> llegada){

            Object [][] salida = new Object[llegada.size()][llegada.get(0).length];

            for(int i=0; i<salida.length;i++){

                String [] temporal = llegada.get(i);

                for (int j=0; j< salida[0].length;j++){

                    salida [i][j] = temporal[j];

                }


            }

            return salida;
        }

        private void regresar(){
        XMLManager miCapturador = new XMLManager();
        miCapturador.setVisible(true);
        }

        private void salir(){
                 int option = JOptionPane.showConfirmDialog(null, "Desea Salir?", "Salir del Sistema",JOptionPane.YES_NO_CANCEL_OPTION);
               if (option ==JOptionPane.YES_OPTION){
                   System.exit(0);
               }
        }


        private void setPanelReporteAnual() {
            String cabecera[];
            List<String[]> datos;
            conn = new Conexion();
            String prov=(String)this.jComboBoxReporteProveedor.getSelectedItem();
            if (prov.equals("Todos")){

                String year =(String)this.jComboBoxReporteAnio.getSelectedItem();
                String cliente=(String) this.jComboBoxReporteCliente.getSelectedItem();
                datos=conn.consultarFacturaPorCliente(cliente,year);
                
                if (datos.isEmpty()){
                    
                    JOptionPane.showMessageDialog(null, "No hay facturas con los campos seleccionados");
                    
                }else{
                    
               String header[]={
                   "Codigo Factura",
                   "RUC",
                   "Proveedor",
                   "Valor sin IVA",
                   "IVA",
                   "Valor con IVA",
                   "Gasto Alimentacion",
                    "Gasto Vestimenta",
                    "Gasto Vivienda",
                    "Gasto Salud",
                    "Gasto Educacion",
                    "Gasto Otros"};
               Object[][] matriz=datos(datos);
               this.reporteMatriz=matriz;
               this.reporteCabezera=header;
               String anio=year;

                temaReporte[0]="cliente";
                temaReporte[1]=cliente;
                temaReporte[2]=anio;
                temaReporte[3]="khe";

               JTable reporteCliente = new JTable(matriz,header);
               this.jScrollPaneReporteCountAnual.setViewportView(reporteCliente);
                }
            }
            else {
               
               String year =(String)this.jComboBoxReporteAnio.getSelectedItem();
               String cliente=(String) this.jComboBoxReporteCliente.getSelectedItem();
               temaReporte[3]=prov;
                datos=conn.consultarFacturaPorProveedor(cliente,year,prov);
                
                 if (datos.isEmpty()){
                    
                    JOptionPane.showMessageDialog(null, "No hay facturas con los campos seleccionados");
                    
                }else{
                
                String header[]={
                   "Numero Facturas",
                   "RUC",
                   "Proveedor",
                   "Gasto Alimentacion",
                    "Gasto Vestimenta",
                    "Gasto Vivienda",
                    "Gasto Salud",
                    "Gasto Educacion",
                    "Gasto Otros"};
               Object[][] matriz=datos(datos);

               this.reporteMatriz=matriz;
               this.reporteCabezera=header;
               String anio=year;

                temaReporte[0]="cliente";
                temaReporte[1]=cliente;
                temaReporte[2]=anio;
                temaReporte[3]="khe";

               reporteCantidadFacturas = new JTable(matriz,header);
               this.jScrollPaneReporteCountAnual.setViewportView(reporteCantidadFacturas);

               jScrollPaneReporteCountAnual.setViewportView(reporteCantidadFacturas);

            }
                 
            }

        }
        
        private void setPanelReporteNegocios() {
            String cabecera[];
            List<String[]> datos;
            conn = new Conexion();
            String prov=(String)this.jComboBoxReporteProveedor.getSelectedItem();
            if (prov.equals("Todos")){

                String year =(String)this.jComboBoxAnioNegocio.getSelectedItem();
                String cliente=(String) this.jComboBoxClienteNegocio.getSelectedItem();
                String tipoGasto =(String) this.jComboBoxTipoGasto.getSelectedItem();
                
                datos=conn.consultarFacturaNegocio(cliente, year, tipoGasto);
                
                if (datos.isEmpty()){
                    
                    JOptionPane.showMessageDialog(null, "No hay facturas con los campos seleccionados");
                    
                }else{
                    
               String header[]={
                   "Nombre Producto",
                   "Nombre Proveedor",
                   "Cantidad total comprada",
                   "Valor total"};
                   
               Object[][] matriz=datos(datos);
               this.reporteMatriz=matriz;
               this.reporteCabezera=header;
               String anio=year;

                temaReporte[0]="cliente";
                temaReporte[1]=cliente;
                temaReporte[2]=anio;
                temaReporte[3]="khe";

               JTable reporteNegocio = new JTable(matriz,header);
               this.jScrollPaneGastoNegocio.setViewportView(reporteNegocio);
                }
            }
            

        }
    
        private void setPanelCantidadFacturas(String nombreCliente){

        //SE INSTANCIAL LA tabla reporteProveedores
        //en el panel jPanelRESULTADOS

                    // TODO add your handling code here:
                conn = new Conexion();

                //con = Conexion.conecxionBDD();

                List<String[]> datos = conn.consultarNumeroFacturas(nombreCliente,jComboBoxReporteAnio.getSelectedItem().toString());

                Object [][] matriz = datos(datos);

                String nombreCabeceras[] = {"Numero de facturas"};



            reporteCantidadFacturas = new JTable(matriz, nombreCabeceras) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column == 2;
                }
            };

            jScrollPaneReporteCountAnual.setViewportView(reporteCantidadFacturas);


    
}
    
    private void generarReportes() {
        
        
        if(this.reporteCabezera==null||this.reporteMatriz==null)
            JOptionPane.showMessageDialog(null, "Realiza una consulta para poder exportar");
        else{
            JOptionPane.showMessageDialog(null, "Selecciona la ubicacion donde deseas guardar los Reportes");
        String path="";
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    
        int returnVal = fc.showOpenDialog(Reportes.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            try {
                //This is where a real application would open the file.
              
              path=file.getCanonicalPath()+"/";
              System.out.println(path);
                                
            } catch (IOException ex) {
                Logger.getLogger(XMLManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se seleccionó ningún directorio.", "Cancelando", 3);
        }
         new ExportaReportes().generar(path,reporteCabezera, this.reporteMatriz,temaReporte );
         JOptionPane.showMessageDialog(null, "Se han generado los reportes en :\n"+path);
        }
       
        
    }

    
}
